org.gradle.jvmargs=-Xmx4G

minecraft_version=1.21.1
enabled_platforms=fabric,neoforge

mod_id=datadrivenvillagers

archives_base_name=datadrivenvillagers
mod_version=1.0.0
maven_group=lion.datadrivenvillagers

architectury_version=13.0.11

fabric_loader_version=0.19.3
fabric_api_version=0.116.17+1.21.1

neoforge_version=21.1.249

yarn_mappings=1.21.1+build.3:v2
# Yarn x NeoForge needs a patch layer, otherwise remapping fails with "Mapping target name conflicts".
yarn_mappings_patch_neoforge_version=1.21+build.6
